services:
  fastapi:
    public: true
    image: fastapi-crud:latest
    build: .
    replicas: 1
    environment:
      - REDIS_URI=redis://default:6VuhH4jPVXEtVza3bdhV@containers-us-west-32.railway.app:6228/ #change this REDIS_URI get it from redistogo.com
      - PYTHON_ENV=prod
      - CACHE_EXPIRATION=180
    ports:
      - 8080
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1000Mi
